version: '3'

services:
  rails:
    build: .
    image: anacatharina/ubuntu-rails-sshd
    volumes:
      - .:/projects
    ports:
      - "3000"
      - "22"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres:/var/lib/potgresql/data
    ports:
      - "5432"
