version: '3'

services:
  rails:
    build: .
    depends_on:
      - db
    image: anacatharina/ubuntu-rails-sshd
    volumes:
      - .:/projects
    ports:
      - "3000"
      - "22"
    networks:
      - my_networks
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres:/var/lib/potgresql/data
    ports:
      - "5432"
    networks:
      my_networks:
        aliases:
          - pgsql

networks:
  my_networks:
