version: '3'

services:
  web:
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
        - app
    ports:
      - 80:80
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres:/var/lib/potgresql/data
    ports:
      - 5432
  app:
    build: .
    volumes:
      - ./rails_app:/rails_app
    environment: 
      - RAILS_ENV=${RAILS_ENV}
    depends_on:
      - db
